# Generated by Django 5.1.1 on 2024-09-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(verbose_name='Модель')),
                ('price', models.TextField(verbose_name='Цена')),
                ('numberFans', models.TextField(verbose_name='Количество вентиляторов')),
                ('turboFrequency', models.TextField(verbose_name='Турбочастота')),
                ('memory_size', models.TextField(verbose_name='Размер памяти')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.DeleteModel(
            name='VideoСard',
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'verbose_name': 'Материнская плата', 'verbose_name_plural': 'Материнские платы'},
        ),
        migrations.AlterModelOptions(
            name='powerunit',
            options={'verbose_name': 'Блок питания', 'verbose_name_plural': 'Блоки питания'},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'verbose_name': 'Процессор', 'verbose_name_plural': 'Процессоры'},
        ),
        migrations.AddField(
            model_name='motherboard',
            name='computerM_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.computer', verbose_name='Материнская плата'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='processors',
            field=models.ManyToManyField(to='computers.processor', verbose_name='Поддерживаемые процессоры'),
        ),
        migrations.AddField(
            model_name='powerunit',
            name='computerPU_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.computer', verbose_name='Блок питания'),
        ),
        migrations.AddField(
            model_name='processor',
            name='computerP_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.computer', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.TextField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='compatibleKernels',
            field=models.TextField(verbose_name='Совместимые ядра'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='model',
            field=models.TextField(verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.TextField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='processorPowerConnector',
            field=models.TextField(verbose_name='Разъем питания процессора'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='supportedMemory',
            field=models.TextField(verbose_name='Поддерживаемая память'),
        ),
        migrations.AlterField(
            model_name='powerunit',
            name='coolingSystem',
            field=models.TextField(verbose_name='Система охлаждения'),
        ),
        migrations.AlterField(
            model_name='powerunit',
            name='model',
            field=models.TextField(verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='powerunit',
            name='networkVoltage',
            field=models.TextField(verbose_name='Сетевое напряжение'),
        ),
        migrations.AlterField(
            model_name='powerunit',
            name='power',
            field=models.TextField(verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='powerunit',
            name='price',
            field=models.TextField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='chipset',
            field=models.TextField(verbose_name='Чипсет'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='frequency',
            field=models.TextField(verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='model',
            field=models.TextField(verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='price',
            field=models.TextField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='socket',
            field=models.TextField(verbose_name='Сокет'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='computerV_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.computer', verbose_name='Видеокарта'),
        ),
    ]
