# Generated by Django 5.1.1 on 2024-09-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_videocard_delete_videoсard_alter_computer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='computerM_FK',
        ),
        migrations.RemoveField(
            model_name='powerunit',
            name='computerPU_FK',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='computerP_FK',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='computerV_FK',
        ),
        migrations.AddField(
            model_name='computer',
            name='computerM_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.motherboard', verbose_name='Компьютер'),
        ),
        migrations.AddField(
            model_name='computer',
            name='computerPU_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.powerunit', verbose_name='Компьютер'),
        ),
        migrations.AddField(
            model_name='computer',
            name='computerP_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.processor', verbose_name='Компьютер'),
        ),
        migrations.AddField(
            model_name='computer',
            name='computerV_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.videocard', verbose_name='Компьютер'),
        ),
    ]
