# Generated by Django 5.1.1 on 2024-10-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_rename_name_computer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='picture',
            field=models.ImageField(null=True, upload_to='computers', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='picture',
            field=models.ImageField(null=True, upload_to='computers', verbose_name='Изображение'),
        ),
    ]
